name: another_network_tool
description: "Scan all devices in your network."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  forui: ^0.16.0
  network_info_plus: ^7.0.0
  network_tools: ^5.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3
  mockito: ^5.6.1
  package_rename: ^1.10.1

flutter:
  assets:
    - assets/network_tools/mac-vendors-export.csv
  uses-material-design: true
