name: Multi-Platform Build

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        platform:
          - { os: ubuntu-latest, target: android }
          - { os: ubuntu-latest, target: linux }
          # - { os: ubuntu-latest, target: web }
          # - { os: macos-latest, target: ios }
          # - { os: macos-latest, target: macos }
          # - { os: windows-latest, target: windows }

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: adopt
      
      - name: Install dependencies
        run: flutter pub get --no-example

      - name: Download and generate build dependencies
        run: bash setup.bash

      - name: Build platform
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          case ${{ matrix.platform.target }} in
            android)
              flutter build apk --release --build-number "$BUILD_NUMBER"
              # flutter build appbundle --release
              ;;
            ios)
              flutter build ios --release --no-codesign --build-number "$BUILD_NUMBER"
              ;;
            macos)
              flutter build macos --release --build-number "$BUILD_NUMBER"
              ;;
            windows)
              flutter build windows --release --build-number "$BUILD_NUMBER"
              ;;
            linux)
              sudo apt-get update -y && \
              sudo apt-get install -y ninja-build libgtk-3-dev && \
              flutter build linux --release --build-number "$BUILD_NUMBER"
              ;;
            web)
              flutter build web --release --build-number "$BUILD_NUMBER"
              ;;
          esac
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.platform.target }}-builds
          path: |
            ${{ matrix.platform.target == 'android' && 'build/app/outputs/flutter-apk/app-release.apk' }}
            ${{ matrix.platform.target == 'ios' && 'build/ios/iphoneos/Runner.app' }}
            ${{ matrix.platform.target == 'macos' && 'build/macos/Build/Products/Release/wlan_local_raffle.app' }}
            ${{ matrix.platform.target == 'windows' && 'build/windows/x64/runner/Release' }}
            ${{ matrix.platform.target == 'linux' && 'build/linux/x64/release/bundle' }}
            ${{ matrix.platform.target == 'web' && 'build/web' }}
          # ${{ matrix.platform.target == 'android' && 'build/app/outputs/bundle/release/app-release.aab' }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/main')
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create and upload GitHub prerelease (automatic releases)
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "dev"
          prerelease: true
          title: "Dev build ${{ steps.date.outputs.date }} (#${{ github.run_number }})"
          files: |
            artifacts/**/app-release.apk
